### ISSUE TITLE
How do we test the trained model?

### ISSUE THREAD

**Issue by sniperwrb** [Unisound/SampleRNN#8]
There is not an "eval.py" or something...
Also, when we are training the model, it does not seem to output anything, either to the screen or to the logdir.

**Comment by xuerq** [comment]
during the training , samples will be generated every 20 steps
https://github.com/Unisound/SampleRNN/blob/master/train.py#L361

and we use Tensorboard to track the loss curve :
tensorboard --logdir=./logdir/train --port=1000

**Comment by sniperwrb** [comment]
Thank you very much!
